# Generated by Django 3.2.5 on 2021-07-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DL', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingValidations',
        ),
        migrations.AddField(
            model_name='user',
            name='docs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='max_docs_allowed',
            field=models.IntegerField(default=5),
        ),
    ]
